version: "3.8"

services:
  db:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Betis1907
      MARIADB_DATABASE: groupandplay
      MARIADB_USER: groupplay
      MARIADB_PASSWORD: group123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: springboot-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_URL: jdbc:mysql://db:3306/groupandplay?useSSL=false&serverTimezone=UTC
      MYSQL_USER: groupplay
      MYSQL_PASS: group123
      DOCKER_ENV: true
    volumes:
      - ./uploads/images:/app/uploads/images

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
