-- Usuarios
CREATE TABLE IF NOT EXISTS users (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(30) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  telephone VARCHAR(20) NOT NULL,
  password VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

-- Juegos
CREATE TABLE IF NOT EXISTS games (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(48) NOT NULL UNIQUE,
  max_players INT(4) UNSIGNED NOT NULL
) ENGINE=InnoDB;

-- Grupos
CREATE TABLE IF NOT EXISTS groups (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  status ENUM('OPEN', 'CLOSED') NOT NULL,
  creation_date DATETIME NOT NULL DEFAULT NOW(),
  comunication ENUM('DISCORD', 'VOICE_CHAT', 'NO_COMMUNICATION') NOT NULL,
  description VARCHAR(256),
  game_id INT(4) UNSIGNED NOT NULL,
  creator_id INT(4) UNSIGNED NOT NULL,  
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Usuarios de un Grupo
CREATE TABLE IF NOT EXISTS users_groups (
  user_id INT(4) UNSIGNED NOT NULL,
  group_id INT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (user_id, group_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE
) ENGINE=InnoDB;
